test action

diff --git a/.github/workflows/phplint.yml b/.github/workflows/phplint.yml
--- a/.github/workflows/phplint.yml
+++ b/.github/workflows/phplint.yml
@@ -20,6 +20,13 @@ jobs:
           coverage: none
           tools: phpcs
       - name: Run linters
+        id: linters
         uses: wearerequired/lint-action@v2
         with:
           php_codesniffer: true
+      - name: Check linter results
+        run: |
+          if [ ${{ steps.linters.outputs.exitcode }} -ne 0 ]; then
+            echo "Linting failed. Please fix the issues before merging.";
+            exit 1;
+          fi
